# Generated by Django 2.0.3 on 2019-07-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_auto_20190703_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpu',
            options={'verbose_name': 'CPU', 'verbose_name_plural': 'CPUs'},
        ),
        migrations.AddField(
            model_name='cpu',
            name='cpuColumn',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cpu',
            name='date',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
