# Generated by Django 2.0.3 on 2019-07-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_auto_20190704_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diskavg',
            name='AvgDiskAvailable',
        ),
        migrations.RemoveField(
            model_name='diskavg',
            name='AvgDiskFree',
        ),
        migrations.RemoveField(
            model_name='diskavg',
            name='date',
        ),
        migrations.AlterField(
            model_name='diskavg',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
